project:
  output-dir: _render/proposal

book:
  title: >
    Evaluating the Moderating Effect of Resilience to Buffer the Impact of Stress on Depression, Anxiety, and Burnout
  sidebar:
    title: Policy and Resilience
    style: docked
  output-file: proposal
  doi: 10.53962/jn77-mprt
  chapters:
    - index.qmd
    - text: Introduction
      href: docs/proposal/intro.qmd
    - text: Literature Review
      href: docs/proposal/litrev.qmd
    - text: Research Framework
      href: docs/proposal/research-framework.qmd
    - text: Methods
      href: docs/proposal/methods.qmd
    - text: Summary
      href: docs/proposal/summary.qmd
    - text: Bibliography
      href: docs/proposal/references.qmd

format:
  pdf:
    toc: true
    lot: true
    lof: true
    linestretch: 1.5
    pdf-engine: xelatex
    template: style/ui.tex
    documentclass: report
    include-in-header:
      text: |
        \usepackage{longtable}
        \usepackage{amsmath}
        \usepackage{amssymb}
        \usepackage{multicol}
        \usepackage{float}
        \floatplacement{figure}{htbp}
        \floatplacement{table}{htbp}
        \usepackage{lscape}
        \newcommand{\blandscape}{\begin{landscape}}
        \newcommand{\elandscape}{\end{landscape}}

logo: fig/logo-ui.png
npm: 2106682703
program: "Community Epidemiology Doctoral Program"
faculty: "Public Health Faculty of the University of Indonesia"
city-date: "Groningen, 14 August 2025"
supervisor:
- "Prof. dr. Mondastri Korib Sudaryo, M.S., D.Sc."
- "Prof. Talitha Feenstra"
version:
  no: 6
  date: 14-08-2025
