project:
  output-dir: _render/intro

book:
  title: >
    Mental Resilience as a Determinant of Burnout, Depression, and Anxiety amidst
    Adversity
  sidebar:
    title: Policy and Resilience
    style: docked
  output-file: introductory-essay
  doi: 10.53962/jn77-mprt
  chapters:
    - index.qmd
    - text: Introduction
      href: qmd/proposal/intro.qmd
    - text: Bibliography
      href: qmd/proposal/references.qmd

format:
  pdf:
    documentclass: scrbook
    toc: true
    lof: true
    lot: true
    include-in-header:
      text: |
        \usepackage{typearea}
        \usepackage{longtable}
        \usepackage{amsmath}
        \usepackage{amssymb}
        \usepackage{multicol}
        \usepackage{float}
        \floatplacement{figure}{htbp}
        \floatplacement{table}{htbp}
