project:
  output-dir: _render/rug

book:
  title: >
    "Project Definition: Mental Resilience as a Determinant of Mental Disorders amidst Adversity"
  sidebar:
    title: Policy and Resilience
    style: docked
  output-file: project-definition
  doi: 10.53962/jn77-mprt
  chapters:
    - index.qmd
    - text: Introduction
      href: docs/rug-essay/intro.qmd
    - text: "Project Definition"
      href: docs/project-definition/project-definition.qmd
    - text: Bibliography
      href: docs/proposal/references.qmd

format:
  pdf:
    documentclass: scrbook
    toc: true
    include-in-header:
      text: |
        \usepackage{typearea}
        \usepackage{longtable}
        \usepackage{amsmath}
        \usepackage{amssymb}
        \usepackage{multicol}
        \usepackage{float}
        \floatplacement{figure}{htbp}
        \floatplacement{table}{htbp}
  docx:
    toc: true
