project:
  type: website
  output-dir: _render/web
  preview:
    port: 1810

website:
  search:
    type: textbox
    copy-button: true
    location: sidebar
  navbar:
    title: false
    left:
      - text: "Home"
        href: index.qmd
      - text: "About"
        href: about.qmd
      - text: "Learning Space"
        href: docs/learning-space/index.qmd
  sidebar:
    title: "Policy and Resilience"
    style: docked
    alignment: right
    contents:
      - text: About
        href: about.qmd
      - text: Bibliography
        href: docs/proposal/references.qmd
